### ISSUE TITLE
How to manually commit the contents of the WAL file to the main database file before db closed？

### ISSUE THREAD

**Issue by coloraven** [marcboeker/go-duckdb#179]
How to manually commit the contents of the WAL file to the main database file while using the appender method for parallel insert data before db closed.
```go
package main

import (
	"context"
	"database/sql/driver"
	"fmt"
	"sync"
	"time"

	"github.com/marcboeker/go-duckdb"
)

func main() {
	connector, err := duckdb.NewConnector("sgk.db", func(execer driver.ExecerContext) error {
		bootQueries := []string{
			"CREATE TABLE IF NOT EXISTS info (ids int,name varchar)",
		}

		for _, query := range bootQueries {
			// Use ExecContext instead of Exec
			_, err := execer.ExecContext(context.Background(), query, nil)
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		fmt.Println(err)
	}
	// defer connector.Close()

	conn, err := connector.Connect(context.Background())
	if err != nil {
		fmt.Println(err)
	}
	// defer conn.Close()
	var wg sync.WaitGroup
	for i := int32(0); i < 10000; i++ {
		wg.Add(1)
		go func(i int32) {
			defer wg.Done()
			appender, err := duckdb.NewAppenderFromConn(conn, "", "info")
			if err != nil {
				fmt.Println(err)
			}
			defer appender.Close()
			err = appender.AppendRow(i, "d")
			if err != nil {
				fmt.Println(err)
			}
		}(i)
	}
	wg.Wait()
	fmt.Println("pause 3s then close conn")
	time.Sleep(3 * time.Second)
	conn.Close()
	fmt.Println("pause 3s then close connector")
	time.Sleep(3 * time.Second)
	connector.Close() // Then the contents of the WAL file commited to the main database file
	fmt.Println("pause 5s then exit program")
	time.Sleep(5 * time.Second)
}
```

**Comment by marcboeker** [comment]
You do not need to create an appender for every row you want to insert. Please create the appender beforehand and use this to append rows to it.

```
appender, err := duckdb.NewAppenderFromConn(conn, "", "info")
if err != nil {
    fmt.Println(err)
}
defer appender.Close()

var wg sync.WaitGroup
for i := int32(0); i < 10000; i++ {
    wg.Add(1)
    go func(i int32) {
	    defer wg.Done()   
	    if err := appender.AppendRow(i, "d"); err != nil {
		    fmt.Println(err)
	    }
    }(i)
}
wg.Wait()
```

**Comment by coloraven** [comment]
> You do not need to create an appender for every row you want to insert. Please create the appender beforehand and use this to append rows to it.
> 
> ```
> appender, err := duckdb.NewAppenderFromConn(conn, "", "info")
> if err != nil {
>     fmt.Println(err)
> }
> defer appender.Close()
> 
> var wg sync.WaitGroup
> for i := int32(0); i < 10000; i++ {
>     wg.Add(1)
>     go func(i int32) {
> 	    defer wg.Done()   
> 	    if err := appender.AppendRow(i, "d"); err != nil {
> 		    fmt.Println(err)
> 	    }
>     }(i)
> }
> wg.Wait()
> ```

then the program will panic with 
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff785d49ff4]

goroutine 7 [running]:
github.com/marcboeker/go-duckdb.setPrimitive[...](0x38?, 0x0?, 0x0)
        C:/Users/white/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/appender.go:452 +0x34
github.com/marcboeker/go-duckdb.initPrimitive[...].func1(0x7ff785e1b1c0?, 0x7ff785d7e560?, {0x7ff785d7e560?, 0x7ff785d58aa0?})
        C:/Users/white/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/appender.go:252 +0x2f
github.com/marcboeker/go-duckdb.(*Appender).appendRowArray(0xc00013e090, {0xc000071f70?, 0x2, 0x0?})
        C:/Users/white/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/appender.go:567 +0x1b2
github.com/marcboeker/go-duckdb.(*Appender).AppendRow(0xc00013e090, {0xc000071f70, 0x2, 0x2})
        C:/Users/white/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.6.1/appender.go:209 +0xd5
main.main.func2(0x0?)
        C:/Users/white/Desktop/go-duckdb/main.go:50 +0xa7
created by main.main in goroutine 1
        C:/Users/white/Desktop/go-duckdb/main.go:48 +0x1c9
```

**Comment by coloraven** [comment]
The focus is on how to commit the contents of the WAL file to the main database file before closing the database connection. This is because when inserting a large amount of data (10+ GB CSV) into DuckDB, it is necessary to commit the contents of the WAL file to the main database file after inserting a certain amount of data, rather than committing all at once at the end. If the program exits unexpectedly, this approach prevents data loss.

**Comment by marcboeker** [comment]
Whats happens when you call `appender.Flush()`? Does that solve your problem? But normally the appended rows should automatically be flushed to disk.

**Comment by coloraven** [comment]
> Whats happens when you call `appender.Flush()`? Does that solve your problem? But normally the appended rows should automatically be flushed to disk.

Unfortunately, neither appender.close nor appender.flush has been able to commit the data from the WAL file to the main database file. I also gave appender.flush a try, but it didn't seem to have any effect. Just to clarify, my concern is about committing data from the WAL file to the main database file, rather than from memory to disk.

**Comment by michaelmdresser** [comment]
@coloraven try `CHECKPOINT;` https://duckdb.org/docs/sql/statements/checkpoint.html

**Comment by coloraven** [comment]
> @coloraven try `CHECKPOINT;` https://duckdb.org/docs/sql/statements/checkpoint.html

no effect,you can test yourself
```go
package main

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"sync"
	"time"

	"github.com/marcboeker/go-duckdb"
)

func main() {
	connector, err := duckdb.NewConnector("test.db", func(execer driver.ExecerContext) error {
		bootQueries := []string{
			"CREATE TABLE IF NOT EXISTS info (ids int,name varchar)",
		}

		for _, query := range bootQueries {
			// Use ExecContext instead of Exec
			_, err := execer.ExecContext(context.Background(), query, nil)
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		fmt.Println(err)
	}
	// defer connector.Close()

	conn, err := connector.Connect(context.Background())
	if err != nil {
		fmt.Println(err)
	}
	// defer conn.Close()
	var wg sync.WaitGroup
	for i := int32(0); i < 10000; i++ {
		wg.Add(1)
		go func(i int32) {
			defer wg.Done()
			appender, err := duckdb.NewAppenderFromConn(conn, "", "info")
			if err != nil {
				fmt.Println(err)
			}
			defer appender.Close()
			err = appender.AppendRow(i, "d")
			if err != nil {
				fmt.Println(err)
			}

			appender.Flush()
		}(i)
	}
	db := sql.OpenDB(connector)
	defer db.Close()
	fmt.Println("\n[Please observe the changes in the WAL file and database file before and after.]\n")
	fmt.Println("Pausing for 3 seconds, Then exec CHECKPOINT.\n")
	db.Exec("CHECKPOINT")
	wg.Wait()
	fmt.Println("Pausing for 3 seconds, Then close conn\n")
	time.Sleep(3 * time.Second)
	conn.Close()
	fmt.Println("Pausing for 3 seconds, Then close connector\n")
	time.Sleep(3 * time.Second)
	connector.Close() // Then the contents of the WAL file commited to the main database file
	fmt.Println("Pausing for 5 seconds, Then exit program\n")
	time.Sleep(5 * time.Second)
}
```

**Comment by taniabogatsch** [comment]
> no need exec checkpoint ,the duckdb will sync data from wal to db file

When inserting a lot of data, DuckDB triggers `AutomaticCheckpoint` (there is a threshold on how much we write to the WAL). So even though you're not calling `CHECKPOINT` explicitly in your last example, there is still a `CHECKPOINT` happening. Because we only truncate the WAL after a successful checkpoint.

Your scenario sounds like we're not monitoring this automatic checkpoint threshold when using the `Appender`. Can you reproduce this in C with the C API? Then, you can directly file a reproduction issue/bug report to DuckDB. My hunch is that this is not an issue caused by go-duckdb. This example probably works in go-duckdb if you're iteratively running `INSERT INTO` without the appender, as you're mimicking the CLI behavior.

**Comment by tim-hilt** [comment]
Same issue happening for me. Using the appender API, I get no errors when flushing and closing the appender, but still - the .wal file is 29 MB whereas the actual .db file is only 11 KB. I think I'll switch to usual inserts, until this is resolved.

See [this commit in my repo](https://github.com/tim-hilt/codescene/tree/5558fec5bed662349168980e58b7ed37bc12eb36) if you want to try it out for yourselves.

Is there anything I can do to help resolve this faster?

**Comment by taniabogatsch** [comment]
Hi, I only came back to looking at this now.

I recently fixed this issue related to the appender and automatic flush/checkpointing: https://github.com/marcboeker/go-duckdb/pull/428. The fix is in the **latest tagged release of go-duckdb: `v2.2.1`.**

> How to manually commit the contents of the WAL file to the main database file while using the appender method for parallel insert data before db closed.

W.r.t the original question - using the explicit `CHECKPOINT` statement seems to work now, can you verify this on your side @coloraven? I altered your code slightly, see the rest of my comment.

The below snippet is a slight alteration of the original issue.
- It runs 1k appenders in parallel, each appending `rowCount` rows.
- It prints the WAL size once immediately after the appends, and once after explicit checkpointing.

My output is:
```
row count: 10000
finished appending: WAL size: 5805548 bytes
explicit checkpoint: hello.db.wal does not exist
closed connector: hello.db.wal does not exist

row count: 100000
finished appending: WAL size: 7936711 bytes
explicit checkpoint: hello.db.wal does not exist
closed connector: hello.db.wal does not exist

row count: 1000000
finished appending: WAL size: 3879440 bytes
explicit checkpoint: hello.db.wal does not exist
closed connector: hello.db.wal does not exist
```

We can see that after ~8MB, no automatic checkpointing has happened after appending.
However, for `rowCount = 1M`, we would expect a significantly bigger WAL size, **if no automatic checkpointing had happened.** So, it looks like DuckDB triggered an automatic checkpoint there.

@tim-hilt, maybe you can decrease DuckDB's automatic checkpointing threshold for your case? (`SET checkpoint_threshold = '1MiB'`). [The default value should be 16MiB](https://duckdb.org/docs/stable/configuration/overview.html#global-configuration-options), so it is still odd that you're seeing a 29MB WAL file. 🤔 
Maybe you can share a snippet similar to mine to reproduce your scenario with DuckDB ignoring the WAL checkpoint threshold?

```Go
package main

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"fmt"
	"log"
	"os"
	"strconv"
	"sync"
	"time"

	"github.com/marcboeker/go-duckdb/v2"
)

const dbName = "hello.db"
const walName = dbName + ".wal"

func check(e error) {
	if e != nil {
		log.Fatal(e)
	}
}

func printWALState(msg string) {
	fi, err := os.Stat(walName)
	if errors.Is(err, os.ErrNotExist) {
		fmt.Printf("%s: %s does not exist\n", msg, walName)
		return
	}
	check(err)
	fmt.Printf("%s: WAL size: %d bytes\n", msg, fi.Size())
}

func runAppends(connector *duckdb.Connector, appenderCount int32, rowCount int32) {
	conn, err := connector.Connect(context.Background())
	check(err)
	defer func() {
		check(conn.Close())
	}()

	var wg sync.WaitGroup
	for i := int32(0); i < appenderCount; i++ {
		wg.Add(1)
		go func(i int32) {
			defer wg.Done()

			appender, e := duckdb.NewAppenderFromConn(conn, "", "info")
			check(e)
			defer func() {
				check(appender.Close())
			}()

			for j := int32(0); j < rowCount; j++ {
				check(appender.AppendRow(j, strconv.Itoa(int(j))))
			}
		}(i)
	}
	wg.Wait()
	printWALState("finished appending")
}

func runScenario(appenderCount int32, rowCount int32) {
	defer func() {
		check(os.Remove(dbName))
	}()

	connector, err := duckdb.NewConnector(dbName, func(execer driver.ExecerContext) error {
		bootQueries := []string{
			`CREATE OR REPLACE TABLE info (ids INT, name VARCHAR)`,
		}
		for _, query := range bootQueries {
			_, err := execer.ExecContext(context.Background(), query, nil)
			check(err)
		}
		return nil
	})
	check(err)
	defer func() {
		time.Sleep(1 * time.Second)
		check(connector.Close())
		printWALState("closed connector")
	}()

	runAppends(connector, appenderCount, rowCount)

	time.Sleep(1 * time.Second)
	db := sql.OpenDB(connector)
	defer func() {
		time.Sleep(1 * time.Second)
		check(db.Close())
		printWALState("explicit checkpoint")
	}()

	_, err = db.Exec(`CHECKPOINT`)
	check(err)
}

func main() {
	// Try to trigger automatic checkpointing.
	s := []int32{10_000, 100_000, 1_000_000}
	for _, rowCount := range s {
		fmt.Printf("row count: %d\n", rowCount)
		runScenario(1000, rowCount)
		fmt.Println()
	}
}
```

**Comment by taniabogatsch** [comment]
I've also replied here: https://github.com/marcboeker/go-duckdb/issues/419#issuecomment-2879901955, with some additional information on checkpointing and compaction in DuckDB.

**Comment by mlafeldt** [comment]
👋 Thanks for opening this issue!

This issue has been moved to https://github.com/duckdb/duckdb-go/issues/18, and I'm closing it here.

Please see https://github.com/marcboeker/go-duckdb/issues/565 for more details.
