### ISSUE TITLE
bug:  panic with Query a table that does not exist

### ISSUE THREAD

**Issue by junhwong** [marcboeker/go-duckdb#19]
```
panic: database/sql/driver: misuse of duckdb driver: Close with active Rows [recovered]
	panic: database/sql/driver: misuse of duckdb driver: Close with active Rows

goroutine 25 [running]:
testing.tRunner.func1.2({0xa00120, 0xba5400})
	/opt/golang/go1.17.2/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/opt/golang/go1.17.2/src/testing/testing.go:1212 +0x218
panic({0xa00120, 0xba5400})
	/opt/golang/go1.17.2/src/runtime/panic.go:1038 +0x215
github.com/marcboeker/go-duckdb.(*stmt).Close(0xc000220480)
	/go/pkg/mod/github.com/marcboeker/go-duckdb@v0.0.0-20220323180549-e23eb52fb6da/statement.go:25 +0x5f
database/sql.(*driverStmt).Close(0xc00028a340)
	/opt/golang/go1.17.2/src/database/sql/sql.go:678 +0x9e
database/sql.(*driverConn).finalClose(0xc000220480)
	/opt/golang/go1.17.2/src/database/sql/sql.go:642 +0xbc
database/sql.(*DB).Close(0xc0002900d0)
	/opt/golang/go1.17.2/src/database/sql/sql.go:904 +0x27e
```

**Comment by marcboeker** [comment]
Could you please share the affected code, as my initial test has thrown the appropriate error:

```
panic: Catalog Error: Table with name users1 does not exist!
Did you mean "users"?
LINE 3:                 FROM users1
             ^
```

**Comment by junhwong** [comment]
@marcboeker the following code can reproduce:

```go
func TestDuckdbPrepareQuery(t *testing.T) {
	dsn := "path/to.db"
	db, err := sql.Open("duckdb", dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	stmt, err := db.PrepareContext(context.TODO(), "select * from user1")
	if err != nil {
		t.Fatal(err)
	}
	defer stmt.Close()

	rows, err := stmt.QueryContext(context.TODO())
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
}

```

**Comment by junhwong** [comment]
@marcboeker and, the following SQL error is incorrect

```sql
select * from tbl col=?
```

expect:  **syntax error**
got: **sql: expected 0 arguments, got 1**

**Comment by junhwong** [comment]
PS:  Any syntax error returns the same error(**expected x arguments, got n**) or an empty error **errors.New("")**

**Comment by marcboeker** [comment]
@junhwong Please check the latest master. Providing insufficient parameters should return an error now. And executing a query with a wrong syntax should also return an error.
